apiVersion: v1
kind: Service
metadata:
  name: emojize-backend
  labels:
    app: emojize-backend
spec:
  ports:
  - name: grpc-web
    port: 9000
  selector:
    app: emojize-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojize-backend
spec:
  selector:
    matchLabels:
      app: emojize-backend
  template:
    metadata:
      labels:
        app: emojize-backend
        version: v1
    spec:
      containers:
      - name: emojize-backend
        image: marceloaguero/emojize-server
        ports:
        - containerPort: 9000
